USE asterisk;

insert into `code_country`(`code`,`country`) values (1,'USA (Canada)');
insert into `code_country`(`code`,`country`) values (20,'Egipt');
insert into `code_country`(`code`,`country`) values (211,'South Sudan');
insert into `code_country`(`code`,`country`) values (212,'Morocco');
insert into `code_country`(`code`,`country`) values (213,'Algeria');
insert into `code_country`(`code`,`country`) values (216,'Tunisia');
insert into `code_country`(`code`,`country`) values (218,'Libya');
insert into `code_country`(`code`,`country`) values (220,'Gambia');
insert into `code_country`(`code`,`country`) values (221,'Senegal');
insert into `code_country`(`code`,`country`) values (222,'Mauritania');
insert into `code_country`(`code`,`country`) values (223,'Mali');
insert into `code_country`(`code`,`country`) values (224,'Guinea');
insert into `code_country`(`code`,`country`) values (225,'Ivory Coast');
insert into `code_country`(`code`,`country`) values (226,'Burkina Faso');
insert into `code_country`(`code`,`country`) values (227,'Niger');
insert into `code_country`(`code`,`country`) values (228,'Togo');
insert into `code_country`(`code`,`country`) values (229,'Benin');
insert into `code_country`(`code`,`country`) values (230,'Mauritius');
insert into `code_country`(`code`,`country`) values (231,'Liberia');
insert into `code_country`(`code`,`country`) values (232,'Sierra Leone');
insert into `code_country`(`code`,`country`) values (233,'Ghana');
insert into `code_country`(`code`,`country`) values (234,'Nigeria');
insert into `code_country`(`code`,`country`) values (235,'Chad');
insert into `code_country`(`code`,`country`) values (236,'Central African Republic');
insert into `code_country`(`code`,`country`) values (237,'Cameroon');
insert into `code_country`(`code`,`country`) values (238,'Cape Verde');
insert into `code_country`(`code`,`country`) values (239,'Sao Tome and Principe');
insert into `code_country`(`code`,`country`) values (240,'Equatorial Guinea');
insert into `code_country`(`code`,`country`) values (241,'Gabon');
insert into `code_country`(`code`,`country`) values (242,'Republic of the Congo');
insert into `code_country`(`code`,`country`) values (243,'Democratic Republic of the Congo');
insert into `code_country`(`code`,`country`) values (244,'Angola');
insert into `code_country`(`code`,`country`) values (245,'Guinea-Bissau');
insert into `code_country`(`code`,`country`) values (246,'British Indian Ocean Territory');
insert into `code_country`(`code`,`country`) values (247,'Ascension Island');
insert into `code_country`(`code`,`country`) values (248,'Seychelles');
insert into `code_country`(`code`,`country`) values (249,'Sudan');
insert into `code_country`(`code`,`country`) values (250,'Rwanda');
insert into `code_country`(`code`,`country`) values (251,'Ethiopia');
insert into `code_country`(`code`,`country`) values (252,'Somalia');
insert into `code_country`(`code`,`country`) values (253,'Djibouti');
insert into `code_country`(`code`,`country`) values (254,'Kenya');
insert into `code_country`(`code`,`country`) values (255,'Tanzania');
insert into `code_country`(`code`,`country`) values (256,'Uganda');
insert into `code_country`(`code`,`country`) values (257,'Burundi');
insert into `code_country`(`code`,`country`) values (258,'Mozambique');
insert into `code_country`(`code`,`country`) values (260,'Zambia');
insert into `code_country`(`code`,`country`) values (261,'Madagascar');
insert into `code_country`(`code`,`country`) values (262,'Reunion');
insert into `code_country`(`code`,`country`) values (263,'Zimbabwe');
insert into `code_country`(`code`,`country`) values (264,'Namibia');
insert into `code_country`(`code`,`country`) values (265,'Malawi');
insert into `code_country`(`code`,`country`) values (266,'Lesotho');
insert into `code_country`(`code`,`country`) values (267,'Botswana');
insert into `code_country`(`code`,`country`) values (268,'Swaziland');
insert into `code_country`(`code`,`country`) values (27,'South Africa');
insert into `code_country`(`code`,`country`) values (290,'Saint Helena');
insert into `code_country`(`code`,`country`) values (2908,'Tristan da Cunha');
insert into `code_country`(`code`,`country`) values (291,'Eritrea');
insert into `code_country`(`code`,`country`) values (297,'Aruba');
insert into `code_country`(`code`,`country`) values (298,'Faroe Islands');
insert into `code_country`(`code`,`country`) values (299,'Greenland');
insert into `code_country`(`code`,`country`) values (30,'Greece');
insert into `code_country`(`code`,`country`) values (31,'Netherlands');
insert into `code_country`(`code`,`country`) values (32,'Belgium');
insert into `code_country`(`code`,`country`) values (33,'France');
insert into `code_country`(`code`,`country`) values (34,'Spain');
insert into `code_country`(`code`,`country`) values (350,'Gibraltar');
insert into `code_country`(`code`,`country`) values (351,'Portugal');
insert into `code_country`(`code`,`country`) values (352,'Luxembourg');
insert into `code_country`(`code`,`country`) values (353,'Ireland');
insert into `code_country`(`code`,`country`) values (354,'Iceland');
insert into `code_country`(`code`,`country`) values (355,'Albania');
insert into `code_country`(`code`,`country`) values (356,'Malta');
insert into `code_country`(`code`,`country`) values (357,'Cyprus');
insert into `code_country`(`code`,`country`) values (358,'Finland');
insert into `code_country`(`code`,`country`) values (359,'Bulgaria');
insert into `code_country`(`code`,`country`) values (36,'Hungary');
insert into `code_country`(`code`,`country`) values (370,'Lithuania');
insert into `code_country`(`code`,`country`) values (371,'Latvia');
insert into `code_country`(`code`,`country`) values (372,'Estonia');
insert into `code_country`(`code`,`country`) values (373,'Moldova');
insert into `code_country`(`code`,`country`) values (37325,'Transnistria');
insert into `code_country`(`code`,`country`) values (374,'Armenia');
insert into `code_country`(`code`,`country`) values (375,'Belarus');
insert into `code_country`(`code`,`country`) values (376,'Andorra');
insert into `code_country`(`code`,`country`) values (377,'Monaco');
insert into `code_country`(`code`,`country`) values (378,'San Marino');
insert into `code_country`(`code`,`country`) values (380,'Ukraine');
insert into `code_country`(`code`,`country`) values (381,'Serbia');
insert into `code_country`(`code`,`country`) values (382,'Montenegro');
insert into `code_country`(`code`,`country`) values (385,'Croatia');
insert into `code_country`(`code`,`country`) values (386,'Slovenia');
insert into `code_country`(`code`,`country`) values (387,'Bosnia and Herzegovina');
insert into `code_country`(`code`,`country`) values (389,'Macedonia');
insert into `code_country`(`code`,`country`) values (39,'Italy');
insert into `code_country`(`code`,`country`) values (40,'Romania');
insert into `code_country`(`code`,`country`) values (41,'Switzerland');
insert into `code_country`(`code`,`country`) values (420,'Czech Republic');
insert into `code_country`(`code`,`country`) values (421,'Slovakia');
insert into `code_country`(`code`,`country`) values (43,'Austria');
insert into `code_country`(`code`,`country`) values (44,'United Kingdom');
insert into `code_country`(`code`,`country`) values (45,'Denmark');
insert into `code_country`(`code`,`country`) values (46,'Sweden');
insert into `code_country`(`code`,`country`) values (47,'Norway');
insert into `code_country`(`code`,`country`) values (48,'Poland');
insert into `code_country`(`code`,`country`) values (49,'Germany');
insert into `code_country`(`code`,`country`) values (500,'Falkland Islands');
insert into `code_country`(`code`,`country`) values (501,'Belize');
insert into `code_country`(`code`,`country`) values (502,'Guatemala');
insert into `code_country`(`code`,`country`) values (503,'El Salvador');
insert into `code_country`(`code`,`country`) values (504,'Honduras');
insert into `code_country`(`code`,`country`) values (505,'Nicaragua');
insert into `code_country`(`code`,`country`) values (506,'Costa Rica');
insert into `code_country`(`code`,`country`) values (507,'Panama');
insert into `code_country`(`code`,`country`) values (508,'Saint-Pierre and Miquelon');
insert into `code_country`(`code`,`country`) values (509,'Haiti');
insert into `code_country`(`code`,`country`) values (51,'Peru');
insert into `code_country`(`code`,`country`) values (52,'Mexico');
insert into `code_country`(`code`,`country`) values (53,'Cuba');
insert into `code_country`(`code`,`country`) values (54,'Argentina');
insert into `code_country`(`code`,`country`) values (55,'Brazil');
insert into `code_country`(`code`,`country`) values (56,'Chile');
insert into `code_country`(`code`,`country`) values (57,'Colombia');
insert into `code_country`(`code`,`country`) values (58,'Venezuela');
insert into `code_country`(`code`,`country`) values (590,'Guadeloupe');
insert into `code_country`(`code`,`country`) values (591,'Bolivia');
insert into `code_country`(`code`,`country`) values (592,'Guyana');
insert into `code_country`(`code`,`country`) values (593,'Ecuador');
insert into `code_country`(`code`,`country`) values (595,'Paraguay');
insert into `code_country`(`code`,`country`) values (596,'Martinique');
insert into `code_country`(`code`,`country`) values (597,'Suriname');
insert into `code_country`(`code`,`country`) values (598,'Uruguay');
insert into `code_country`(`code`,`country`) values (60,'Malaysia');
insert into `code_country`(`code`,`country`) values (61,'Australia');
insert into `code_country`(`code`,`country`) values (62,'Indonesia');
insert into `code_country`(`code`,`country`) values (63,'Philippines');
insert into `code_country`(`code`,`country`) values (64,'New Zealand');
insert into `code_country`(`code`,`country`) values (65,'Singapore');
insert into `code_country`(`code`,`country`) values (66,'Thailand');
insert into `code_country`(`code`,`country`) values (673,'Brunei');
insert into `code_country`(`code`,`country`) values (674,'Nauru');
insert into `code_country`(`code`,`country`) values (675,'Papua New Guinea');
insert into `code_country`(`code`,`country`) values (676,'Tonga');
insert into `code_country`(`code`,`country`) values (677,'Solomon Islands');
insert into `code_country`(`code`,`country`) values (678,'Vanuatu');
insert into `code_country`(`code`,`country`) values (679,'Fiji');
insert into `code_country`(`code`,`country`) values (680,'Palau');
insert into `code_country`(`code`,`country`) values (681,'Wallis and Futuna');
insert into `code_country`(`code`,`country`) values (682,'Cook Islands');
insert into `code_country`(`code`,`country`) values (683,'Niue');
insert into `code_country`(`code`,`country`) values (684,'ormerly American Samoa');
insert into `code_country`(`code`,`country`) values (685,'Samoa');
insert into `code_country`(`code`,`country`) values (686,'Kiribati');
insert into `code_country`(`code`,`country`) values (687,'New Caledonia');
insert into `code_country`(`code`,`country`) values (688,'Tuvalu');
insert into `code_country`(`code`,`country`) values (689,'French Polynesia');
insert into `code_country`(`code`,`country`) values (690,'Tokelau');
insert into `code_country`(`code`,`country`) values (691,'Federated States of Micronesia');
insert into `code_country`(`code`,`country`) values (692,'Marshall Islands');
insert into `code_country`(`code`,`country`) values (7,'Russia');
insert into `code_country`(`code`,`country`) values (76,'Kazakhstan');
insert into `code_country`(`code`,`country`) values (77,'Kazakhstan');
insert into `code_country`(`code`,`country`) values (81,'Japan');
insert into `code_country`(`code`,`country`) values (82,'South Korea');
insert into `code_country`(`code`,`country`) values (84,'Vietnam');
insert into `code_country`(`code`,`country`) values (850,'North Korea');
insert into `code_country`(`code`,`country`) values (851,'nassigned');
insert into `code_country`(`code`,`country`) values (852,'Hong Kong');
insert into `code_country`(`code`,`country`) values (853,'Macau');
insert into `code_country`(`code`,`country`) values (854,'nassigned');
insert into `code_country`(`code`,`country`) values (855,'Cambodia');
insert into `code_country`(`code`,`country`) values (856,'Laos');
insert into `code_country`(`code`,`country`) values (86,'China');
insert into `code_country`(`code`,`country`) values (880,'Bangladesh');
insert into `code_country`(`code`,`country`) values (886,'Taiwan');
insert into `code_country`(`code`,`country`) values (90,'Turkey');
insert into `code_country`(`code`,`country`) values (91,'India');
insert into `code_country`(`code`,`country`) values (92,'Pakistan');
insert into `code_country`(`code`,`country`) values (93,'Afghanistan');
insert into `code_country`(`code`,`country`) values (94,'Sri Lanka');
insert into `code_country`(`code`,`country`) values (95,'Myanmar');
insert into `code_country`(`code`,`country`) values (960,'Maldives');
insert into `code_country`(`code`,`country`) values (961,'Lebanon');
insert into `code_country`(`code`,`country`) values (962,'Jordan');
insert into `code_country`(`code`,`country`) values (963,'Syria');
insert into `code_country`(`code`,`country`) values (964,'Iraq');
insert into `code_country`(`code`,`country`) values (965,'Kuwait');
insert into `code_country`(`code`,`country`) values (966,'Saudi Arabia');
insert into `code_country`(`code`,`country`) values (967,'Yemen');
insert into `code_country`(`code`,`country`) values (968,'Oman');
insert into `code_country`(`code`,`country`) values (970,'Palestine');
insert into `code_country`(`code`,`country`) values (971,'United Arab Emirates');
insert into `code_country`(`code`,`country`) values (972,'Israel');
insert into `code_country`(`code`,`country`) values (973,'Bahrain');
insert into `code_country`(`code`,`country`) values (974,'Qatar');
insert into `code_country`(`code`,`country`) values (975,'Bhutan');
insert into `code_country`(`code`,`country`) values (976,'Mongolia');
insert into `code_country`(`code`,`country`) values (977,'Nepal');
insert into `code_country`(`code`,`country`) values (98,'Iran');
insert into `code_country`(`code`,`country`) values (992,'Tajikistan');
insert into `code_country`(`code`,`country`) values (993,'Turkmenistan');
insert into `code_country`(`code`,`country`) values (994,'Azerbaijan');
insert into `code_country`(`code`,`country`) values (995,'Georgia');
insert into `code_country`(`code`,`country`) values (996,'Kyrgyzstan');
insert into `code_country`(`code`,`country`) values (998,'Uzbekistan');
